name: ðŸš¦ BPA Quality Check

on:
  push:
    paths:
      - '**/src/*.Report/**'
      - '**/src/*.SemanticModel/**'
    branches:
      - "feature/**"
      - "features/**"

  workflow_dispatch:

jobs:
  run-bpa-checks:                     # anciennement: bpa
    name: ðŸ§ª Run Power BI Best Practices
    runs-on: windows-latest
    
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ“Š Semantic Model â€“ BPA Analysis
        run: .\scripts\bpa-semanticmodel.ps1 -path "." -src "./src/*.SemanticModel"
      
      - name: ðŸ“ˆ Report â€“ BPA Analysis
        run: .\scripts\bpa-report.ps1 -path "." -src "./src/*.Report"
