name: bpa

on:
  push:
    paths:
      - '**/src/*.Report/**'
      - '**/src/*.SemanticModel/**'
    branches:
      - "feature/**"
      - "features/**"

  workflow_dispatch:
        
jobs:
  bpa:   
    runs-on: windows-latest
    
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Semantic Models BPA
        run: .\scripts\bpa-semanticmodel.ps1 -path "." -src "./src/*.SemanticModel"
      
      - name: Reports BPA
        run: .\scripts\bpa-report.ps1 -path "." -src "./src/*.Report"
